
###服务启动端口号
server:
  port: 8300
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-member
    redis:
      host: 114.67.108.221
      port: 6379
      password: root123456
    ###数据库相关连接
    datasource:
      username: root
      password: root1234
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://114.67.108.221:3306/shop_member?useUnicode=true&characterEncoding=UTF-8

swagger:
  base-package: cn.llyong.shop.member.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目。
  version: 1.0
  terms-of-service-url: www.llyong.cn
  contact:
    name: llyong
    email: 9999999999@qq.com

####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    cn.llyong.shop.member.mapper: DEBUG
